spring.application.name=final

spring.datasource.url=${jSPRING_DATASOURCE_URL:jdbc:postgresql://ep-snowy-art-ahdq9hsb-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_SiPNycOJ81Ug}
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:danieldanieldaniel0163867567899HARISUTULLAZJHJZKKJKD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
cloudinary.cloud-name=daniel
cloudinary.api-key=376847455868448
cloudinary.api-secret=DK6sVPGk2oo2OMcLrUV4Zw_htD8
logging.level.org.springframework.security=DEBUG
logging.level.com.example.demo.Security=DEBUG
# Afficher les messages d'erreur de validation (@NotBlank etc) dans Postman
server.error.include-message=always
server.error.include-binding-errors=always