spring.application.name=final

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-noisy-lab-atlg3con-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_yG7atOmzJq8B}
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:danieldanieldaniel0163867567899HARISUTULLAZJHJZKKJKD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
logging.level.org.springframework.security=DEBUG
logging.level.com.example.demo.Security=DEBUG
# Afficher les messages d'erreur de validation (@NotBlank etc) dans Postman
server.error.include-message=always
server.error.include-binding-errors=always